"use client";

import { useState, useEffect } from "react";
import { Artifact } from "@/lib/orchestrator";
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Badge } from '@/components/ui/badge';
import { FileText, Calendar, Zap, Megaphone, CheckCircle } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import rehypeHighlight from 'rehype-highlight';
import 'highlight.js/styles/github-dark.css';

// Tab configuration with icons
const tabConfig = [
  {
    id: "PRD",
    label: "PRD",
    title: "Product Requirements Document",
    icon: FileText,
    description: "Problem statement, target users, key features, and success metrics",
    placeholder: "The Product Requirements Document will appear here once generated by the Product Manager..."
  },
  {
    id: "Timeline", 
    label: "Timeline",
    title: "Project Timeline",
    icon: Calendar,
    description: "Project milestones, deadlines, and risk management",
    placeholder: "The project timeline will appear here once generated by the Project Manager..."
  },
  {
    id: "Engineering",
    label: "Engineering",
    title: "Engineering Plan", 
    icon: Zap,
    description: "Technical architecture, task breakdown, and implementation details",
    placeholder: "The engineering plan will appear here once generated by the Senior Engineer..."
  },
  {
    id: "Marketing",
    label: "Marketing",
    title: "Marketing Strategy",
    icon: Megaphone, 
    description: "Brand positioning, landing copy, and marketing materials",
    placeholder: "The marketing strategy will appear here once generated by the Marketing Lead..."
  }
];

interface ArtifactTabsProps {
  artifacts: Record<string, Artifact>;
  onArtifactUpdate?: (artifactId: string, newContent: string) => void;
  className?: string;
}

interface EditableArtifactProps {
  artifact?: Artifact;
  tabInfo: typeof tabConfig[0];
  onUpdate?: (content: string) => void;
}

function EditableArtifact({ artifact, tabInfo, onUpdate }: EditableArtifactProps) {
  const [content, setContent] = useState(artifact?.content || "");
  const [isEditing, setIsEditing] = useState(false);
  const [hasChanges, setHasChanges] = useState(false);

  useEffect(() => {
    setContent(artifact?.content || "");
    setHasChanges(false);
  }, [artifact]);

  const handleContentChange = (newContent: string) => {
    setContent(newContent);
    setHasChanges(newContent !== (artifact?.content || ""));
  };

  const handleSave = () => {
    if (hasChanges && onUpdate) {
      onUpdate(content);
      setHasChanges(false);
    }
    setIsEditing(false);
  };

  const handleCancel = () => {
    setContent(artifact?.content || "");
    setHasChanges(false);
    setIsEditing(false);
  };

  const isEmpty = !artifact || !artifact.content;

  return (
    <div className="h-full flex flex-col">
      {/* Header */}
      <div className="flex-shrink-0 border-b border-border p-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-3">
            <tabInfo.icon className="h-6 w-6 text-primary" />
            <div>
              <h3 className="text-lg font-semibold text-foreground">
                {tabInfo.title}
              </h3>
              <p className="text-sm text-muted-foreground">
                {tabInfo.description}
              </p>
            </div>
          </div>
          
          {!isEmpty && (
            <div className="flex items-center space-x-2">
              {hasChanges && (
                <span className="text-xs text-orange-300 bg-orange-950/50 px-2 py-1 rounded-full">
                  Unsaved changes
                </span>
              )}
              
              <Badge variant={artifact ? 'default' : 'secondary'}>
                <CheckCircle className="w-3 h-3 mr-1" />
                {artifact ? 'Complete' : 'In Progress'}
              </Badge>
            </div>
          )}
        </div>
        
      </div>

      {/* Content */}
      <div className="flex-1 p-4">
        {isEmpty ? (
          <div className="h-full flex items-center justify-center">
            <div className="text-center">
              <tabInfo.icon className="h-12 w-12 text-muted-foreground mx-auto mb-4" />
              <h4 className="text-lg font-medium text-foreground mb-2">
                No {tabInfo.label} Yet
              </h4>
              <p className="text-muted-foreground max-w-sm">
                {tabInfo.placeholder}
              </p>
            </div>
          </div>
        ) : (
          <div className="h-full">
            {isEditing ? (
              <textarea
                value={content}
                onChange={(e) => handleContentChange(e.target.value)}
                className="w-full h-full p-4 border border-border rounded-lg resize-none focus:ring-2 focus:ring-primary focus:border-transparent font-mono text-sm bg-background text-foreground"
                placeholder={tabInfo.placeholder}
              />
            ) : (
              <div className="h-full overflow-y-auto">
                <div className="p-4 bg-muted/30 rounded-lg border border-border h-full">
                  <div className="prose prose-invert max-w-none text-sm leading-relaxed">
                    <ReactMarkdown
                      rehypePlugins={[rehypeHighlight]}
                      components={{
                        h1: ({ children }) => <h1 className="text-2xl font-bold text-foreground mb-4">{children}</h1>,
                        h2: ({ children }) => <h2 className="text-xl font-semibold text-foreground mb-3">{children}</h2>,
                        h3: ({ children }) => <h3 className="text-lg font-medium text-foreground mb-2">{children}</h3>,
                        p: ({ children }) => <p className="text-foreground mb-3 leading-relaxed">{children}</p>,
                        ul: ({ children }) => <ul className="list-disc pl-6 mb-3 text-foreground">{children}</ul>,
                        ol: ({ children }) => <ol className="list-decimal pl-6 mb-3 text-foreground">{children}</ol>,
                        li: ({ children }) => <li className="mb-1">{children}</li>,
                        strong: ({ children }) => <strong className="font-semibold text-foreground">{children}</strong>,
                        em: ({ children }) => <em className="italic text-foreground">{children}</em>,
                        code: ({ children }) => <code className="bg-muted px-1.5 py-0.5 rounded text-sm font-mono text-foreground">{children}</code>,
                        pre: ({ children }) => <pre className="bg-muted p-4 rounded-lg overflow-x-auto mb-4">{children}</pre>,
                        blockquote: ({ children }) => <blockquote className="border-l-4 border-primary pl-4 italic text-muted-foreground mb-4">{children}</blockquote>,
                      }}
                    >
                      {artifact?.content}
                    </ReactMarkdown>
                  </div>
                </div>
              </div>
            )}
          </div>
        )}
      </div>
      
      {/* Footer with timestamp and edit controls */}
      {!isEmpty && (
        <div className="flex-shrink-0 px-4 py-2 bg-muted/30 border-t border-border">
          <div className="flex items-center justify-between">
            <div className="text-xs text-muted-foreground">
              <span>Created by {artifact?.agentName} • {new Date(artifact?.timestamp || new Date()).toLocaleString()}</span>
            </div>
            <div className="flex space-x-2">
              {isEditing ? (
                <>
                  <button
                    onClick={handleSave}
                    className="px-3 py-1 bg-primary text-primary-foreground text-sm rounded-md hover:bg-primary/90 transition-colors"
                  >
                    Save
                  </button>
                  <button
                    onClick={handleCancel}
                    className="px-3 py-1 bg-muted text-muted-foreground text-sm rounded-md hover:bg-muted/80 transition-colors"
                  >
                    Cancel
                  </button>
                </>
              ) : (
                <button
                  onClick={() => setIsEditing(true)}
                  className="px-3 py-1 bg-muted text-muted-foreground text-sm rounded-md hover:bg-muted/80 transition-colors"
                >
                  Edit
                </button>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export default function ArtifactTabs({ artifacts, onArtifactUpdate, className = "" }: ArtifactTabsProps) {
  const [activeTab, setActiveTab] = useState("PRD");

  // Get artifact for current tab
  const getArtifactForTab = (tabId: string): Artifact | undefined => {
    return Object.values(artifacts).find(artifact => 
      artifact.type === tabId || 
      (tabId === "Engineering" && artifact.type === "architecture") ||
      (tabId === "Marketing" && (artifact.type === "landing_copy" || artifact.type === "brand_assets"))
    );
  };

  // Count available artifacts
  const artifactCounts = tabConfig.reduce((acc, tab) => {
    acc[tab.id] = getArtifactForTab(tab.id) ? 1 : 0;
    return acc;
  }, {} as Record<string, number>);

  const totalArtifacts = Object.values(artifactCounts).reduce((sum, count) => sum + count, 0);

  const handleArtifactUpdate = (tabId: string, newContent: string) => {
    const artifact = getArtifactForTab(tabId);
    if (artifact && onArtifactUpdate) {
      onArtifactUpdate(artifact.id, newContent);
    }
  };

  return (
    <div className={`flex flex-col h-full ${className}`}>
      <Tabs value={activeTab} onValueChange={setActiveTab} className="flex flex-col h-full">
        <div className="flex items-center justify-between px-4 py-3 border-b border-border/50">
          <div className="flex items-center gap-2">
            <h2 className="text-lg font-semibold">Deliverables</h2>
            <Badge variant="secondary" className="text-xs">
              {totalArtifacts}/{tabConfig.length}
            </Badge>
          </div>
        </div>
        
        <TabsList className="grid w-full grid-cols-4 h-auto p-1 bg-muted/30">
          {tabConfig.map((tab) => {
            const hasArtifact = artifactCounts[tab.id] > 0;
            const IconComponent = tab.icon;
            
            return (
              <TabsTrigger
                key={tab.id}
                value={tab.id}
                className="flex items-center gap-2 py-3 data-[state=active]:bg-background data-[state=active]:shadow-sm"
              >
                <IconComponent className="h-4 w-4" />
                <span className="hidden sm:inline">{tab.label}</span>
                {hasArtifact && (
                  <CheckCircle className="h-3 w-3 text-green-500" />
                )}
              </TabsTrigger>
            );
          })}
        </TabsList>

        {/* Tab Content */}
        {tabConfig.map((tab) => (
          <TabsContent key={tab.id} value={tab.id} className="flex-1 mt-0 h-full">
            <EditableArtifact
              artifact={getArtifactForTab(tab.id)}
              tabInfo={tab}
              onUpdate={(content) => handleArtifactUpdate(tab.id, content)}
            />
          </TabsContent>
        ))}
      </Tabs>
    </div>
  );
}

